name:                hs-librsvg
version:             0.1.0.0
github:              albertov/hs-librsvg
license:             LGPL
license-file:        LICENSE
author:              Alberto Valverde
maintainer:          alberto@toscat.net
# copyright:

# Metadata used when publishing your package
# synopsis:            Short description of your package
category:            Data

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.

dependencies:
- base >= 4.7 && < 5
- cairo
- inline-c
- bytestring
- mtl

pkg-config-dependencies: librsvg-2.0


library:
  source-dirs: src

ghc-options:
- -Wall
- -j


executables:
  svgtopdf:
    main:            Main.hs
    source-dirs:     app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -eventlog
    dependencies:
    - hs-librsvg
    - optparse-generic


tests:
  svg-test:
    main: Main.hs
    source-dirs: test
    dependencies:
    - hs-librsvg
    - hspec
